from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Alembic is being set up now, before any model exists in app/models/
# (see CLAUDE.md section 4 -- the domain model is still a draft pending
# ebook review). Learning-context reasoning (CLAUDE.md section 6): wiring
# migrations from day one, against an empty Base.metadata, confirms the
# whole chain -- config.py -> database.py -> Alembic -> CockroachDB --
# actually works *before* any real schema exists to blame for failures.
# The first migration to ever run against this project's history will
# therefore be a genuine "create the domain tables" migration, not a
# retrofit bolted on after the schema had already drifted from what
# Alembic thinks it manages.
#
# CockroachDB compatibility note: CockroachDB speaks the PostgreSQL wire
# protocol, so the standard SQLAlchemy "postgresql" dialect and Alembic's
# autogenerate work here without a dedicated CockroachDB dialect. Known
# rough edges to watch for once real migrations are autogenerated:
#   - CockroachDB auto-creates an index backing most foreign key columns;
#     autogenerate may propose a "duplicate" explicit index or a spurious
#     DROP INDEX/CREATE INDEX diff against one it thinks it owns. Review
#     autogenerated index diffs by hand rather than trusting them blindly.
#   - Some ALTER TABLE forms Postgres runs in one statement (e.g. certain
#     column type changes, adding a column with a volatile default) are
#     unsupported or require CockroachDB's own multi-step online-schema-
#     change workflow. Autogenerate can produce a migration that is valid
#     Postgres DDL but fails against CockroachDB.
#   - Postgres-only constructs (certain index types, exclusion
#     constraints) have no CockroachDB equivalent and won't autogenerate
#     correctly if ever introduced.
# None of this blocks the empty baseline in this step; it matters once
# real ALTER-heavy migrations start getting autogenerated.

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Read the DB connection URL from the same Settings object database.py
# uses, instead of alembic.ini's sqlalchemy.url -- so there is exactly one
# place (config.py) that knows how to build the connection string, and
# the COCKROACH_DATABASE env var (currently "crdb_calisteniaapp_db") only
# has to be correct in one spot.
from app.config import settings  # noqa: E402
from app.database import Base  # noqa: E402

config.set_main_option("sqlalchemy.url", settings.database_url)

# Base.metadata is empty until real models are added under app/models/ --
# expected for this step. Once models exist and import into Base, this is
# what lets `alembic revision --autogenerate` diff them against the DB.
target_metadata = Base.metadata

# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
