"""Add exercise.level_variant, make level nullable, widen unique constraint

Revision ID: df3166695497
Revises: b9f6688550b9
Create Date: 2026-07-19 21:25:32.075385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3166695497'
down_revision: Union[str, Sequence[str], None] = 'b9f6688550b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('level_variant', sa.String(length=1), nullable=True))
    op.alter_column('exercise', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # CockroachDB quirk (see alembic/env.py): unique constraints are
    # backed by an index, and CockroachDB doesn't support dropping them
    # via `ALTER TABLE ... DROP CONSTRAINT` -- autogenerate produced that
    # form since it's valid Postgres DDL, but CockroachDB requires
    # `DROP INDEX ... CASCADE` instead (this is the exact "review
    # autogenerated index diffs by hand" case env.py warns about).
    op.execute("DROP INDEX exercise@uq_exercise_line_level CASCADE")
    op.create_unique_constraint('uq_exercise_line_level_variant', 'exercise', ['progression_line', 'level', 'level_variant'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Same CockroachDB DROP INDEX quirk as upgrade() above.
    op.execute("DROP INDEX exercise@uq_exercise_line_level_variant CASCADE")
    op.create_unique_constraint(op.f('uq_exercise_line_level'), 'exercise', ['progression_line', 'level'], postgresql_nulls_not_distinct=False)
    op.alter_column('exercise', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exercise', 'level_variant')
    # ### end Alembic commands ###
